# Generated by Django 3.1.4 on 2020-12-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0002_auto_20201230_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
