# Generated by Django 3.1.4 on 2021-01-02 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0003_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos'),
            preserve_default=False,
        ),
    ]
