# Generated by Django 3.1.4 on 2021-01-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0005_measurment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurment',
        ),
    ]
