# Generated by Django 3.1.4 on 2021-01-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0006_delete_measurment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='submission_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
