# Generated by Django 3.1.4 on 2021-01-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0009_remove_car_car_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='submission_data',
        ),
    ]
