# Generated by Django 3.1.4 on 2021-01-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0011_auto_20210104_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Images',
            field=models.ImageField(blank=True, default=None, upload_to='photos'),
        ),
    ]
