# Generated by Django 3.1.4 on 2021-01-04 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicing', '0015_auto_20210104_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos'),
            preserve_default=False,
        ),
    ]
